version: '3.8'

volumes: 
  webapi_database_volume:
    name: sample_clean_architecture_template_db
networks: 
    sample_microservice_network:

services:
  webapi:
    container_name: sample_clean_architecture_template_webapi
    image: sp/sample_clean_architecture_template/webapi
    build:
      dockerfile: ./src/WebApi/Dockerfile
      context: ./
      args: 
        - Configuration=Debug
        - RunTests=true
    ports: 
      - "5001:443"
      - "5000:80"
    environment: 
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__AppDatabase=Host=webapi_database;Database=sample_clean_architecture_template;Username=sa;Password=postgres;Port=5432"
    networks: 
      - sample_microservice_network
    depends_on: 
      - webapi_database
  webapi_database:
    container_name: sample_clean_architecture_template_db
    image: sp/sample_clean_architecture_template/database
    build:
      dockerfile: ./Dockerfile
      context: ./src/DataModel/
    ports:
      - "5432:5432"
    volumes: 
      - webapi_database_volume:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample_clean_architecture_template
    networks: 
      - sample_microservice_network      